version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: pgdb
      POSTGRES_DB: prova_adonis
    ports:
      - '5433:5432'
  app:
    depends_on:
      - database
    build: .
    command: npm start
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app
